In [1]:
import pandas as pd

In [4]:
s = pd.Series(fruits)

In [2]:
print(pd.__version__)

2.2.3

In [6]:
fruits = ['apple', 'banana', 'cherry']
print(fruits)

['apple', 'banana', 'cherry']

In [9]:
s = pd.Series(fruits, index = ['A', 'B', 'C'])

In [10]:
print(s)

A     apple
B    banana
C    cherry
dtype: object

In [11]:
d = {'a':10,'b':20,'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [28]:
# DataFrames
students = {'Roll_no': [101, 102, 103, 104, 105],
           'Name': ['Ali', 'Ahmad', 'Umer', 'Zubair', 'Tayyab'],
           'Subject': ['OOP', 'Database', 'Software Engineering', 'OS', 'Programing'],
           'Marks': [80, 87, 67, 56, 92]}

In [4]:
df = pd.DataFrame(students)

In [5]:
df

   Roll_no    Name               Subject  Marks
0      101     Ali                   OOP     80
1      102   Ahmad              Database     87
2      103    Umer  Software Engineering     67
3      104  Zubair                    OS     56
4      105  Tayyab            Programing     92

In [6]:
df['Name']

0       Ali
1     Ahmad
2      Umer
3    Zubair
4    Tayyab
Name: Name, dtype: object

In [7]:
df[['Name', 'Marks']]

     Name  Marks
0     Ali     80
1   Ahmad     87
2    Umer     67
3  Zubair     56
4  Tayyab     92

In [29]:
df['Percentage'] = df['Marks']/200 * 100

In [30]:
df

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [16]:
df.drop('Percentage')

KeyError: "['Percentage'] not found in axis"

In [17]:
# Remove Percentage Column
df.drop('Percentage',axis=1)

   Roll_no    Name               Subject  Marks
0      101     Ali                   OOP     80
1      102   Ahmad              Database     87
2      103    Umer  Software Engineering     67
3      104  Zubair                    OS     56
4      105  Tayyab            Programing     92

In [18]:
df.drop(columns = ['Percentage', 'Name'])

   Roll_no               Subject  Marks
0      101                   OOP     80
1      102              Database     87
2      103  Software Engineering     67
3      104                    OS     56
4      105            Programing     92

In [31]:
df.drop(['Percentage', 'Name'], axis = 1)

   Roll_no               Subject  Marks
0      101                   OOP     80
1      102              Database     87
2      103  Software Engineering     67
3      104                    OS     56
4      105            Programing     92

In [21]:
df.drop(3)

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
4      105  Tayyab            Programing     92        46.0

In [22]:
df.drop([3, 4])

   Roll_no   Name               Subject  Marks  Percentage
0      101    Ali                   OOP     80        40.0
1      102  Ahmad              Database     87        43.5
2      103   Umer  Software Engineering     67        33.5

In [23]:
df.drop([3: 5])

SyntaxError: invalid syntax (1032413164.py, line 1)

In [25]:
df.drop('Percentage', axis = 1, inplace = True)

In [33]:
df_new = df.drop('Percentage', axis = 1)

In [34]:
df_new

   Roll_no    Name               Subject  Marks
0      101     Ali                   OOP     80
1      102   Ahmad              Database     87
2      103    Umer  Software Engineering     67
3      104  Zubair                    OS     56
4      105  Tayyab            Programing     92

In [35]:
df

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [37]:
# loc(locate)
# iloc(index locate)
df.loc[1]

Roll_no            102
Name             Ahmad
Subject       Database
Marks               87
Percentage        43.5
Name: 1, dtype: object

In [38]:
df.loc[1: 3]

   Roll_no    Name               Subject  Marks  Percentage
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0

In [39]:
df.loc[1: 3, ['Roll_no', 'Marks']]

   Roll_no  Marks
1      102     87
2      103     67
3      104     56

In [40]:
df.loc[:, 'Name']

0       Ali
1     Ahmad
2      Umer
3    Zubair
4    Tayyab
Name: Name, dtype: object

In [42]:
df[['Roll_no', 'Name']].loc[1: 3]

   Roll_no    Name
1      102   Ahmad
2      103    Umer
3      104  Zubair

In [43]:
df

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [45]:
df_update = df_new.set_index('Roll_no')

In [46]:
df_update

           Name               Subject  Marks
Roll_no
101         Ali                   OOP     80
102       Ahmad              Database     87
103        Umer  Software Engineering     67
104      Zubair                    OS     56
105      Tayyab            Programing     92

In [47]:
df_update.loc[105]

Name           Tayyab
Subject    Programing
Marks              92
Name: 105, dtype: object

In [48]:
df_update

           Name               Subject  Marks
Roll_no
101         Ali                   OOP     80
102       Ahmad              Database     87
103        Umer  Software Engineering     67
104      Zubair                    OS     56
105      Tayyab            Programing     92

In [50]:
df_update.iloc[1: 3, [0, -1]]

          Name  Marks
Roll_no
102      Ahmad     87
103       Umer     67

In [51]:
df_water = pd.read_csv('water_potability (1).csv')

In [53]:
df_water.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [54]:
df_water.head(10)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
5,5.584087,188.313324,28748.687739,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0
6,10.223862,248.071735,28749.716544,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0
7,8.635849,203.361523,13672.091764,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0
8,NaN,118.988579,14285.583854,7.804174,268.646941,389.375566,12.706049,53.928846,3.595017,0
9,11.180284,227.231469,25484.508491,9.077200,404.041635,563.885481,17.927806,71.976601,4.370562,0

In [55]:
df_water.head(20)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
5,5.584087,188.313324,28748.687739,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0
6,10.223862,248.071735,28749.716544,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0
7,8.635849,203.361523,13672.091764,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0
8,NaN,118.988579,14285.583854,7.804174,268.646941,389.375566,12.706049,53.928846,3.595017,0
9,11.180284,227.231469,25484.508491,9.077200,404.041635,563.885481,17.927806,71.976601,4.370562,0
10,7.360640,165.520797,32452.614409,7.550701,326.624353,425.383419,15.586810,78.740016,3.662292,0
11,7.974522,218.693300,18767.656682,8.110385,NaN,364.098230,14.525746,76.485911,4.011718,0
12,7.119824,156.704993,18730.813653,3.606036,282.344050,347.715027,15.929536,79.500778,3.445756,0
13,NaN,150.174923,27331.361962,6.838223,299.415781,379.761835,19.370807,76.509996,4.413974,0
14,7.496232,205.344982,28388.004887,5.072558,NaN,444.645352,13.228311,70.300213,4.777382,0
15,6.347272,186.732881,41065.234765,9.629596,364.487687,516.743282,11.539781,75.071617,4.376348,0
16,7.051786,211.049406,30980.600787,10.094796,NaN,315.141267,20.397022,56.651604,4.268429,0
17,9.181560,273.813807,24041.326280,6.904990,398.350517,477.974642,13.387341,71.457362,4.503661,0
18,8.975464,279.357167,19460.398131,6.204321,NaN,431.443990,12.888759,63.821237,2.436086,0
19,7.371050,214.496610,25630.320037,4.432669,335.754439,469.914551,12.509164,62.797277,2.560299,0

In [56]:
df_water.head(100)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
...,...,...,...,...,...,...,...,...,...,...
95,6.140878,197.876090,26687.874483,7.587196,329.231853,548.072761,15.836330,41.263648,5.359460,0
96,7.077874,220.670540,23873.378210,6.181840,341.987234,333.050786,10.661799,90.297770,4.764508,0
97,5.488314,135.802362,21485.153195,8.187416,280.603287,441.331137,14.860263,88.287346,5.066786,0
98,7.205559,120.327615,24627.867560,6.202469,289.768697,418.433290,13.643147,63.733732,3.710053,0
99,9.177870,163.274828,20868.331219,7.726040,320.421432,426.994393,10.214275,62.430926,3.108770,0

In [59]:
pd.set_option('display.max_rows', None)

In [60]:
df_water.head(100)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
5,5.584087,188.313324,28748.687739,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0
6,10.223862,248.071735,28749.716544,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0
7,8.635849,203.361523,13672.091764,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0
8,NaN,118.988579,14285.583854,7.804174,268.646941,389.375566,12.706049,53.928846,3.595017,0
9,11.180284,227.231469,25484.508491,9.077200,404.041635,563.885481,17.927806,71.976601,4.370562,0
10,7.360640,165.520797,32452.614409,7.550701,326.624353,425.383419,15.586810,78.740016,3.662292,0
11,7.974522,218.693300,18767.656682,8.110385,NaN,364.098230,14.525746,76.485911,4.011718,0
12,7.119824,156.704993,18730.813653,3.606036,282.344050,347.715027,15.929536,79.500778,3.445756,0
13,NaN,150.174923,27331.361962,6.838223,299.415781,379.761835,19.370807,76.509996,4.413974,0
14,7.496232,205.344982,28388.004887,5.072558,NaN,444.645352,13.228311,70.300213,4.777382,0
15,6.347272,186.732881,41065.234765,9.629596,364.487687,516.743282,11.539781,75.071617,4.376348,0
16,7.051786,211.049406,30980.600787,10.094796,NaN,315.141267,20.397022,56.651604,4.268429,0
17,9.181560,273.813807,24041.326280,6.904990,398.350517,477.974642,13.387341,71.457362,4.503661,0
18,8.975464,279.357167,19460.398131,6.204321,NaN,431.443990,12.888759,63.821237,2.436086,0
19,7.371050,214.496610,25630.320037,4.432669,335.754439,469.914551,12.509164,62.797277,2.560299,0
20,NaN,227.435048,22305.567414,10.333918,NaN,554.820086,16.331693,45.382815,4.133423,0
21,6.660212,168.283747,30944.363591,5.858769,310.930858,523.671298,17.884235,77.042318,3.749701,0
22,NaN,215.977859,17107.224226,5.607060,326.943978,436.256194,14.189062,59.855476,5.459251,0
23,3.902476,196.903247,21167.500099,6.996312,NaN,444.478883,16.609033,90.181676,4.528523,0
24,5.400302,140.739062,17266.593422,10.056852,328.358241,472.874073,11.256381,56.931906,4.824786,0
25,6.514415,198.767351,21218.702871,8.670937,323.596349,413.290450,14.900000,79.847843,5.200885,0
26,3.445062,207.926260,33424.768678,8.782147,384.007006,441.785876,13.805902,30.284597,4.184397,0
27,NaN,145.768181,13224.935639,7.906445,304.001993,298.990666,12.729525,49.536849,4.004871,0
28,NaN,266.421018,26362.965012,7.700063,395.389490,364.480107,10.348951,53.008381,3.991564,0
29,NaN,148.153061,15193.413474,9.046833,307.011793,563.804743,16.568656,52.676185,6.038185,0
30,7.181449,209.625601,15196.229987,5.994679,338.336431,342.111286,7.922598,71.537953,5.088860,0
31,9.825490,190.756618,19677.892466,6.757541,NaN,452.836235,16.899038,47.081971,2.857472,0
32,10.433291,117.791230,22326.892046,8.161505,307.707509,412.986834,12.890709,65.733478,5.057311,0
33,7.414148,235.044534,32555.852537,6.845952,387.175316,411.983364,10.244815,44.489297,3.160624,0
34,NaN,232.280452,14787.206265,5.474915,NaN,383.981723,12.166937,86.080727,5.029167,0
35,5.115817,191.952743,19620.545329,6.060713,323.836384,441.748379,10.966486,49.238231,3.902089,0
36,3.641630,183.908722,24752.072460,5.538314,286.059556,456.860096,9.034067,73.594657,3.464353,0
37,5.618064,304.235912,17281.975168,6.101084,NaN,399.471566,12.265002,81.588992,2.896547,0
38,NaN,143.453731,19942.273218,5.890755,NaN,427.130671,22.469892,53.124094,2.907564,0
39,9.267188,198.614395,24683.723566,6.110612,328.077533,396.876949,16.471969,30.383315,4.324005,0
40,NaN,233.858996,11703.923907,4.599388,309.039320,349.399633,18.338893,42.677465,3.510004,0
41,5.331940,194.874065,16658.876503,7.993830,316.675162,335.120398,10.180514,59.572714,4.434820,0
42,7.145772,238.689929,28780.340432,6.814029,385.975650,332.032706,11.093163,66.138045,5.182591,0
43,9.920691,202.817483,9973.934059,6.882248,337.350529,333.192470,23.917601,71.833624,4.690707,0
44,4.758439,183.349454,21568.428779,4.731349,NaN,403.944168,18.668229,66.912400,4.542801,0
45,5.702926,216.850474,35606.440177,7.184351,NaN,504.638260,16.140790,77.536184,4.137739,0
46,6.953864,209.638293,10575.186281,4.462707,315.606594,391.184315,13.285334,87.390889,3.195710,0
47,10.682966,173.375498,15758.740621,5.570784,307.352586,323.807913,10.090870,78.472784,3.999775,0
48,NaN,129.890572,34415.853146,6.321929,304.535224,470.329169,18.599410,72.403634,4.405586,0
49,8.757257,200.191400,21536.224687,4.915101,317.882900,404.717799,13.768323,47.930872,3.626135,0
50,NaN,168.388431,27492.307307,7.046225,299.820478,383.795020,16.182066,75.729434,3.048057,0
51,7.809632,100.457615,12013.550629,5.212315,247.200826,605.220124,9.611349,66.084174,2.447444,0
52,6.652488,145.010172,19871.788448,4.961066,288.052192,545.974994,10.942024,71.727414,3.742090,0
53,9.147197,211.714142,11920.610836,7.230795,339.751919,527.708910,18.275312,47.634885,3.794532,0
54,10.560745,181.893366,21783.651033,6.991260,340.390378,456.556402,16.482835,34.252049,3.964686,0
55,7.484255,260.092173,30616.615149,9.379134,NaN,404.670777,15.934484,66.621027,4.781188,0
56,8.520807,238.335112,28779.650011,8.282808,381.649323,481.318803,6.016337,39.091171,3.940605,0
57,4.999414,190.287050,24323.865903,7.230164,324.893038,405.330482,8.236558,99.427385,4.460684,0
58,NaN,157.801194,16963.625012,8.335619,300.044234,360.995994,12.823861,71.717005,4.405386,0
59,NaN,155.055727,20557.240432,8.187319,NaN,290.180983,16.622255,59.622057,4.089908,0
60,3.906078,233.402835,32144.799934,6.994840,348.359448,269.449051,9.654126,63.743064,3.902880,0
61,6.391354,213.017830,20965.478309,5.375560,327.650543,369.338121,13.758105,17.915723,3.923749,0
62,NaN,229.485694,35729.692709,8.810843,384.943779,296.397547,16.927092,NaN,3.855602,0
63,8.692092,195.143739,24656.239679,8.231900,NaN,398.345418,12.380771,48.440725,4.477960,0
64,8.085760,127.739674,32653.910360,6.534237,NaN,416.239630,11.119659,78.275050,4.068689,0
65,6.203978,212.306618,21815.074148,7.873992,NaN,362.108004,14.933013,63.873820,5.215689,0
66,5.058109,238.569380,34873.934523,8.983276,374.433505,669.725086,13.353181,76.521800,5.106656,0
67,NaN,103.464759,27420.167425,8.417305,NaN,485.974500,11.351133,67.869964,4.620793,0
68,NaN,211.200526,12830.484134,4.502117,326.961518,333.329848,16.045148,49.898406,3.439740,0
69,7.261551,179.889788,24964.777703,5.837086,349.269271,501.182781,17.287713,50.993006,3.636364,0
70,7.160467,183.089310,6743.346066,3.803036,277.599099,428.036344,9.799625,90.035374,3.884891,0
71,5.704765,116.299330,33223.581529,7.050503,297.078153,504.378681,9.001820,48.147031,4.157533,0
72,6.217273,130.944464,19460.382819,7.092463,300.131272,556.653710,14.083608,57.897075,5.325833,0
73,8.679935,242.228667,22984.050951,7.518765,NaN,352.942588,18.704409,69.907902,3.873470,0
74,NaN,219.300914,14859.466424,5.598327,344.442394,425.213575,15.771834,49.352001,4.655917,0
75,6.897322,211.360167,25650.777643,6.766010,NaN,383.014310,13.934788,90.523330,5.022784,0
76,3.514546,158.732076,23029.663614,6.821679,286.522847,307.379142,9.712232,79.850929,3.762615,0
77,3.722500,163.639747,37962.167991,6.684570,326.694018,467.562973,14.567269,50.577979,3.662838,0
78,6.455005,176.683973,24468.048390,5.756930,314.799598,477.581346,16.245504,57.729724,2.293431,0
79,7.316805,217.522862,31903.399812,9.865048,376.937972,425.913400,8.992754,69.509220,3.508373,0
80,1.844538,233.764343,28689.595778,7.724432,NaN,410.387264,15.611859,54.299444,5.013463,0
81,5.519126,168.728583,12531.601921,7.730723,NaN,443.570372,18.099078,NaN,3.758996,0
82,7.408985,204.961750,9566.122270,6.505923,311.452663,504.145994,11.532144,81.106938,3.772421,0
83,5.976770,258.952732,27267.981861,7.648599,383.657152,514.118920,12.256790,82.469798,2.994671,0
84,6.395359,133.834229,23827.275015,5.127747,266.908428,573.400295,9.833875,95.026609,4.191218,0
85,6.209642,195.417721,13116.707712,7.879348,NaN,417.241656,7.507662,70.547387,3.612520,0
86,6.762833,232.075177,27159.384345,7.884991,350.445293,465.413775,13.863965,64.812257,4.916579,0
87,9.918717,199.181251,21470.278305,6.799841,329.178429,430.507707,15.966043,59.292273,3.385508,0
88,10.155440,300.292476,12652.362979,6.655126,398.647786,487.459131,9.347634,67.919789,5.002467,0
89,8.721727,206.369682,28608.052076,6.325442,377.404538,506.938353,13.553751,42.381484,2.555027,0
90,NaN,197.979783,17153.306163,7.659204,329.280315,575.114694,11.870981,69.109836,4.383922,0
91,NaN,199.107886,29721.911630,6.869690,357.303221,420.709591,9.226619,55.294283,3.355165,0
92,6.099647,237.919927,20416.840996,8.457831,NaN,291.104837,19.270054,93.138009,3.172790,0
93,9.026788,253.217074,27965.072146,6.588374,373.553235,588.319651,16.145732,59.124451,2.019042,0
94,6.953372,203.146547,11609.109055,5.495738,304.283193,551.143337,9.387781,55.958006,3.651866,0
95,6.140878,197.876090,26687.874483,7.587196,329.231853,548.072761,15.836330,41.263648,5.359460,0
96,7.077874,220.670540,23873.378210,6.181840,341.987234,333.050786,10.661799,90.297770,4.764508,0
97,5.488314,135.802362,21485.153195,8.187416,280.603287,441.331137,14.860263,88.287346,5.066786,0
98,7.205559,120.327615,24627.867560,6.202469,289.768697,418.433290,13.643147,63.733732,3.710053,0
99,9.177870,163.274828,20868.331219,7.726040,320.421432,426.994393,10.214275,62.430926,3.108770,0

In [61]:
df_water.tail(10)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
3266,8.372910,169.087052,14622.745494,7.547984,NaN,464.525552,11.083027,38.435151,4.906358,1
3267,8.989900,215.047358,15921.412018,6.297312,312.931022,390.410231,9.899115,55.069304,4.613843,1
3268,6.702547,207.321086,17246.920347,7.708117,304.510230,329.266002,16.217303,28.878601,3.442983,1
3269,11.491011,94.812545,37188.826022,9.263166,258.930600,439.893618,16.172755,41.558501,4.369264,1
3270,6.069616,186.659040,26138.780191,7.747547,345.700257,415.886955,12.067620,60.419921,3.669712,1
3271,4.668102,193.681735,47580.991603,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1
3272,7.808856,193.553212,17329.802160,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1
3273,9.419510,175.762646,33155.578218,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1
3274,5.126763,230.603758,11983.869376,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1
3275,7.874671,195.102299,17404.177061,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1

In [62]:
df_water.head(10)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
5,5.584087,188.313324,28748.687739,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,0
6,10.223862,248.071735,28749.716544,7.513408,393.663396,283.651634,13.789695,84.603556,2.672989,0
7,8.635849,203.361523,13672.091764,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,0
8,NaN,118.988579,14285.583854,7.804174,268.646941,389.375566,12.706049,53.928846,3.595017,0
9,11.180284,227.231469,25484.508491,9.077200,404.041635,563.885481,17.927806,71.976601,4.370562,0

In [63]:
df_water.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

In [65]:
df_water.isna().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [67]:
print(df_water.isna().sum().sum())

1434

In [68]:
df_water2 = df_water.dropna()

In [69]:
df_water2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2011 entries, 3 to 3271
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               2011 non-null   float64
 1   Hardness         2011 non-null   float64
 2   Solids           2011 non-null   float64
 3   Chloramines      2011 non-null   float64
 4   Sulfate          2011 non-null   float64
 5   Conductivity     2011 non-null   float64
 6   Organic_carbon   2011 non-null   float64
 7   Trihalomethanes  2011 non-null   float64
 8   Turbidity        2011 non-null   float64
 9   Potability       2011 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 172.8 KB

In [72]:
df_water3 = df_water.fillna(df_water.mean())

In [73]:
df_water3.isna().sum()

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [74]:
df_water3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ph               3276 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          3276 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3276 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB